### ISSUE TITLE
Transfer to ParticularLabs

### ISSUE THREAD

**Issue by andreasohlund** [fhalim/NServiceBus.Serializers.SystemXml#2]
https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/#transferring-to-an-organization

I've made you and admin so you should be able to transfer to https://github.com/orgs/ParticularLabs

Let me know if it works?

**Comment by fhalim** [comment]
Repo moved to https://github.com/ParticularLabs/NServiceBus.Serializers.SystemXml. Should be good to go.

**Comment by andreasohlund** [comment]
👍
